<?xml version="1.0"?>
<robot name="car_chassis_2diff" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.14159265359"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="motor_mass" value="0.1"/>
    <xacro:property name="caster_mass" value="0.05"/>
    <xacro:property name="wheel_radius" value="0.03"/>
    <xacro:property name="wheel_length" value="0.015"/>
    <xacro:property name="motor_radius" value="0.01"/>
    <xacro:property name="motor_length" value="0.05"/>
    <xacro:property name="caster_radius" value="0.01"/>

    <xacro:property name="wheel_joint_x" value="0.0"/>
    <xacro:property name="wheel_joint_y" value="0.025"/>
    <xacro:property name="wheel_joint_z" value="0.0"/>
    <xacro:property name="motor_joint_x" value="-0.03"/>
    <xacro:property name="motor_joint_y" value="0.1"/>
    <xacro:property name="motor_joint_z" value="-0.02"/>

    <material name="blue">
        <color rgba="0.5 0.5 1 0.8"/>
    </material>
    <material name="white">
        <color rgba="0.6 0.6 0.6 1"/>
    </material>

    <!-- inertial calculater start -->
    <xacro:macro name="sphere_inertial" params="m r">
        <inertial>
            <mass value="${m}" />
            <inertia 
            ixx="${2*m*r*r/5}" ixy="0" ixz="0"
            iyy="${2*m*r*r/5}" iyz="0" izz="${2*m*r*r/5}" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_inertial" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia 
            ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
            iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="box_inertial" params="m x y z">
        <inertial>
            <mass value="${m}" />
            <inertia 
            ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
            iyy="${m*(x*x+z*z)/12}" iyz="0" izz="${m*(x*x+y*y)/12}" />
        </inertial>
    </xacro:macro>
    <!-- inertial calculater end -->

    <!-- entity macro start -->
    <xacro:macro name="motor" params="loc_prefix l_r">
        <joint name="base_${loc_prefix}_motor_joint" type="fixed">
            <origin xyz="${motor_joint_x} ${l_r*motor_joint_y} ${motor_joint_z}" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${loc_prefix}_motor" />
        </joint>

        <link name="${loc_prefix}_motor">
            <visual>
                <origin xyz="0 0 0" rpy="${l_r*PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${motor_radius}" length ="${motor_length}"/>
                </geometry>
                <material name="blue" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${l_r*PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${motor_radius}" length ="${motor_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial m="${motor_mass}" r="${motor_radius}" h="${motor_length}" />
        </link>
        <gazebo reference="${loc_prefix}_motor">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="wheel" params="loc_prefix l_r">
        <joint name="${loc_prefix}_wheel_joint" type="continuous">
            <origin xyz="${wheel_joint_x} ${l_r*wheel_joint_y} ${wheel_joint_z}" rpy="0 0 0" />
            <parent link="${loc_prefix}_motor" />
            <child link="${loc_prefix}_wheel_link" />
            <axis xyz="0 1 0" />
        </joint>

        <link name="${loc_prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${l_r*PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length ="${wheel_length}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${l_r*PI/2} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length ="${wheel_length}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <gazebo reference="${loc_prefix}_wheel_link">
            <material>Gazebo/Orange</material>
        </gazebo>
        <transmission name="${loc_prefix}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${loc_prefix}_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${loc_prefix}_wheel_joint">
                <hardwareInterface>VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>
        <xacro:motor loc_prefix="${loc_prefix}" l_r="${l_r}" />
    </xacro:macro>

    <xacro:macro name="caster">
        <joint name="base_caster_joint" type="fixed">
            <origin xyz="0.1 0 -0.04" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="caster_link" />
        </joint>
        <link name="caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.01" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 0.1 1" />
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="0.01" />
                </geometry>
            </collision>
            <xacro:sphere_inertial m="${caster_mass}" r="${caster_radius}" />
        </link>
    </xacro:macro>
    <xacro:macro name="base">
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="0.08" radius="0.17" />
                </geometry>
                <material name="yellow">
                    <color rgba="0.9 0.9 0.1 0.5" />
                </material>
            </visual>
        </link>    
    </xacro:macro>
    <!-- entity macro end -->

    <!-- base start -->
    <link name="base_footprint">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius-wheel_joint_z-motor_joint_z}" rpy="0 0 0"  />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>
    <!-- base end -->

    <xacro:base />
    <xacro:wheel loc_prefix="lf" l_r="1" />
    <xacro:wheel loc_prefix="rt" l_r="-1" />
    <xacro:caster />
    
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <updateRate>100</updateRate>
            <leftJoint>lf_wheel_joint</leftJoint>
            <rightJoint>rt_wheel_joint</rightJoint>
            <wheelSeparation>${2*(motor_joint_y+wheel_joint_y)}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <wheelAcceleration>1.0</wheelAcceleration>
            <wheelTorque>5</wheelTorque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>
</robot>